[package]
name = "rit"
version = "0.1.0"
authors = ["Vlad Nedelcu <nedelcuvd@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.18.2"
sha2 = "0.10.8"
structopt = "0.3.26"
